version: "3"
services:
  app:
    container_name: oceanstyle
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: oracle.fiap.com.br
      DB_PORT: 1521
      DB_NAME: orcl
      DB_USER: rm98078
      DB_PASSWORD: 261202
      JAVA_OPTS: "-Xms256m -Xmx512m"
    volumes:
      - app_data:/path/to/app/data
    networks:
      - oceanstyle_network

networks:
  oceanstyle_network:

volumes:
  app_data:
