version: "3"

services:
  app:
    container_name: oceanstyle
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: oceanstyle_db
      DB_USER: root
      DB_PASSWORD: password
      JAVA_OPTS: "-Xms256m -Xmx512m"
    volumes:
      - app_data:/path/to/app/data
    networks:
      - oceanstyle_network
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: oceanstyle_db
    ports:
      - "3306:3306"
    networks:
      - oceanstyle_network

networks:
  oceanstyle_network:

volumes:
  app_data:
